Design changes
elementary-br/website pull request #24
Opened 2018-06-07 01:21 UTC by geovannimp

- Change colors based on new elementaty pallete
- Fix responsive layout
- Change sizes to follow forum guideline
- Fixed some code indentation
- Remove unnecessary js code

2018-06-07 13:26 UTC, PabloDinella approved these changes
Pra mim tá ok, apenas mudaria o JS pra inglês, mas pode ser num próximo commit

2018-06-08 14:53 UTC, leonardo-lemos requested changes
Eu acho que a altura do menu poderia ser menos, e o espaço das margens laterais também, para se parecer mais com o menu do fórum.

2018-06-08 18:27 UTC, geovannimp commented
@leonardo-lemos Na altura do menu tu fala do header? Pois ele esta do mesmo tanho que o forum :thinking: 
A questão das margens vou dar uma conferida para deixar igual

2018-06-11 15:53 UTC, leonardo-lemos commented
@geovannimp Me desculpe, eu me confundi, a altura realmente é a mesma, só falta trabalhar as margens mesmo 😄

2018-06-14 12:45 UTC, naaando requested changes

2018-06-14 12:45 UTC, naaando commented on assets/css/custom.css
> +  .footer-content > ul:not(.social-icon-list) > li:first-child {
Invés de usar uma "exceção" acho que ficaria melhor especificar a classe e tirar o copyright da lista de links por que o separador está começando já no primeiro link
``.footer-content > .copyright {
    width: 100%;
    display: block;
    text-align: center;
  }``

![screen shot 2018-06-14 at 09 37 46](https://user-images.githubusercontent.com/12532760/41412531-b19e9370-6fb6-11e8-9907-672428938d15.png)

2018-06-14 12:45 UTC, naaando commented on index.html
>            <li><p>© 2018 elementary Brasil</p></li>
Tirar esse item da lista e adicionar a classe copyright talvez?!

2024-01-18 16:55 UTC, closed without merging